name: Build

on:
  [workflow_dispatch, push, pull_request]
  
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      run:
        dotnet restore
        
    - name: Build
      run: msbuild .\ChartConverter.sln  /restore /t:Rebuild /t:ChartConverter /p:Configuration="Release" 

    - name: Create Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartConverter
        path: ${{github.workspace}}\ChartConverter\bin\Release\net8.0
